FROM node:lts as builder

# USER root

WORKDIR /usr/vue-light-bootstrap-dashboard-master/app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build

RUN ls

FROM nginx:stable-alpine as production-stage

COPY --from=builder /usr/vue-light-bootstrap-dashboard-master/app /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]