FROM node:16-alpine as builder

WORKDIR /usr/vue-light-bootstrap-dashboard-master/app

COPY package.* .

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:stable-alpine as production-stage

COPY --from=builder /usr/vue-light-bootstrap-dashboard-master/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]