version: '3.7'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app_talloflix_front
    volumes: 
      - .:/app
    
    working_dir: /app
    restart: always
    ports:
      - 8080:8000