version: '3.7'

services:
  admin-tallosflix:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app_talloflix_front
    ports:
      - 3006:8080
    restart: always
    volumes: 
      - .:/usr/vue-light-bootstrap-dashboard-master/app
    tty: true
    networks:
      - api-tallos-flix
    
networks:
  api-tallos-flix:
    driver: bridge
    