version: '3.7'

services:
  admin-tallosflix:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app_talloflix_front
    ports:
      - 8080:8000
    restart: always
    volumes: 
      - .:/app
    tty: true
    networks:
      - api-tallos-flix

networks:
  api-tallos-flix:
    driver: bridge
    